spring:
  datasource:
    url: jdbc:mysql://27.96.135.97:3306/twitch_clone?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: user

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      default_batch_fetch_size: 100
      hibernate:
        format_sql: true